### ISSUE TITLE
Networking ARP Module

### ISSUE THREAD

**Issue by bob-crutchley** [bob-crutchley/courseware#124]
Module for ARP , use ARP Poisoning as a Task.
This module would serve as a practical implementation for understanding how the ARP works.

- Which targets to select (victim device for target 1 and default gateway for target 2)
  - How to select which victim device
  - How to find out the default gateway
- What to look for in Wireshark (HTTP requests mainly)

Ettercap can be used to start the MITM attack, then Wireshark can be used to analyse the packets of the targeted devices.
Note that the target device must of course be on the same network.
I also ran into issues when trying this if the target device is on Wifi when the machine I'm using is on Ethernet and vice versa.

**Comment by nickrstewarttds** [comment]
I'll pick this up for all but the ARP spoofing task mate
